[project]
name = "hello"
version = "0.1.0"
description = "An example Django app running in Docker."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django==5.2",
  "celery==5.5.0",
  "django-debug-toolbar==5.1.0",
  "gunicorn==23.0.0",
  "psycopg==3.2.6",
  "redis==5.2.1",
  "ruff==0.11.2",
  "setuptools==78.1.0",
  "whitenoise==6.9.0",
  "djangorestframework==3.15.0",  # Add this line
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = [
  "I", # format import statements
  "B", # bugbear
  "S", # bandit
]
ignore = [
  "B904", # `raise ... from err` # TODO probably should fix our code
  "S113", # `requests` call without timeout
]